
# makefile for introduce_program

CLASS_PATH=/home/minh/School/Learning/20222/OOP/Lab/NguyenQuangMinh_20184293/Lab01/bin
RUN_FILE=hust.soict.dsai.garbage.GarbageCreator
all: compile

compile: 
	javac @Configure/options.sh @Configure/sources.sh

run:
	java -cp $(CLASS_PATH) $(RUN_FILE)