
# makefile for checking number of test of 2 arrays if they
# are equal

CC=gcc
CFLAGS=-g -Wall
all: arrayEquality

arrayEquality: arrayEquality.c 
	$(CC) $(CFLAGS) -o arrayEquality.o arrayEquality.c 

clean:
	rm arrayEquality.o